import cv2
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import colors as clr
img = cv2.imread('coins.jpg', 0)
gray = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
ret, thresh = cv2.threshold(img, 80, 255, cv2.THRESH_BINARY)
ker = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (105 , 105))
open = cv2.morphologyEx (thresh, cv2.MORPH_OPEN, ker)
erosion = cv2.erode(thresh , ker , iterations = 1)
plt.imshow(erosion, cmap='gray')
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()
big = cv2.dilate(erosion , ker ,iterations = 1)
plt.imshow(big, cmap='gray')
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()
ker2 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(10,10))
dilbig = cv2.dilate(open,ker2,iterations = 1)
erbig = cv2.erode(open,ker2,iterations = 1)
bigframe = dilbig - erbig
plt.imshow(bigframe, cmap='gray')
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()
ret1, labels= cv2.connectedComponents (dilbig)
(bigcoin, _) = cv2.findContours(open, cv2.RETR_LIST,
 cv2.CHAIN_APPROX_NONE)
cv2.drawContours(gray, bigcoin, -1, (0, 0, 255), 6)
cv2.imshow("Result", gray)
cv2.waitKey(0)
print("The number of big coins is %i " % len(bigcoin))
ker1 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (10,10))
ersmall = cv2.erode((thresh-open),ker1,iterations = 1)
dilsmall = cv2.dilate(ersmall,ker1,iterations = 1)
plt.imshow(dilsmall)
cv2.waitKey(0)
cv2.destroyAllWindows()ker3 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(10,10) )
dil = cv2.dilate(dilsmall, ker3, iterations = 1)
er = cv2.erode (dilsmall, ker3, iterations = 1)
frame= dil - er
plt.imshow(er, cmap='gray')
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()
ret2, labels = cv2.connectedComponents (frame)
(smallcoin, _) = cv2.findContours(dilsmall, cv2.RETR_LIST,
 cv2.CHAIN_APPROX_NONE)
cv2.drawContours(gray, smallcoin, -1, (255, 0, 0), 6)
cv2.imshow("Result", gray)
cv2.waitKey(0)
print("The number of small coins is %i " % len(smallcoin))
h = len(smallcoin)*50 + len(bigcoin)*100
print("The total in the picture is %dh cents" % h)